# from leolani.speech_synthesis.system.glow_tts import GlowTextToSpeech
from leolani.speech_synthesis.system.wavenet_api import WavenetAPITextToSpeech
from leolani.speech_synthesis.system.wavernn import WaveRNNTextToSpeech
from leolani.speech_synthesis.system.mozilla_tts import MozillaTextToSpeech
